title: 改造人009资源站
email: ll631@qq.com
description: > # this means to ignore newlines until "baseurl:"
  这是日本漫画家石森章太郎老师所作SF漫画《サイボーグ009》(改造人009)的
  相关资源下载整理及原作&衍伸作品介绍站。本站由个人管理，与原作及石森Pro
  没有任何关系。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  LChuo

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
encoding: utf-8
