
title: 改造人009资源站
email: ll631@qq.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: https://lchuo.github.io/testblog/
url: https://github.co

github_username:  LChuo

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
encoding: utf-8
